add task4-1
Minkerr/Programming1Semester pull request #2
Opened 2024-03-28 21:06 UTC by Minkerr

2024-04-01 09:35 UTC, yurii-litvinov requested changes

2024-04-01 09:35 UTC, yurii-litvinov commented on task4-1/binaryAddition.c
> +#define INT_SIZE 32
```suggestion
#define INT_SIZE (sizeof(int) * 8)
```
Согласно стандарту, размер int определяется реализацией, никто не обещает, что он равен 32.

2024-04-01 09:35 UTC, yurii-litvinov commented on task4-1/binaryAddition.c
> +    printBinaryNumber(convertedNum);
Совершенно внезапно. decimalToBinary должна переводить число в битовый массив, печатать не должна. Это нарушение SRP.

2024-04-01 09:35 UTC, yurii-litvinov commented on task4-1/binaryAddition.c
> +    int sign = 0;
sign и вообще какая-то специальная работа со знаками не нужны, арифметическое переполнение сделает своё дело. Вы же выкладываете битовое представление числа в массив, и тут перекладываете биты из массива обратно в ячейку памяти (хоть и арифметическими операциями, хотя можно было бы побитовыми) — если исходно было отрицательное число, отрицательное и получится.

2024-04-01 09:35 UTC, yurii-litvinov commented on task4-1/binaryAddition.c
> +void reverse(int arr[], int n) {
reverse нигде не вызывается, однако она есть в заголовочном файле и на неё даже есть тест. Всё это можно убрать вообще :)

2024-04-01 09:35 UTC, yurii-litvinov commented on task4-1/binaryAddition.h
> +void reverse(int arr[], int n);
Надо комментарии

2024-04-01 09:35 UTC, yurii-litvinov commented on task4-1/binaryAdditionTest.c
> +    int bin[32] = {};
Используйте INT_SIZE. А для этого надо его вынести в заголовочный файл, но в принципе по логике вещей это разумно — это размер выходного массива в функции конвертации.

2024-04-01 09:35 UTC, yurii-litvinov commented on task4-1/binaryAdditionTest.c
> +    int binary[32];
Инициализируйте всё, даже массивы, в месте объявления, во избежание ошибок использования неинициализированной переменной

2024-04-01 09:35 UTC, yurii-litvinov commented on task4-1/binaryAdditionTest.c
> +    int res[32];
Даже res как имя переменной не годится

2024-04-01 09:35 UTC, yurii-litvinov commented on task4-1/main.c
> +    runAllTestsTask4();
Тут тоже, надо возвращать ненулевой код возврата, если тесты не прошли, и нулевой, если всё ок.

2024-04-01 18:04 UTC, yurii-litvinov requested changes
А у Вас всё ещё удаление main.c в диффах, а не должно быть

2024-04-01 18:04 UTC, yurii-litvinov commented on task4-1/binaryAddition.h
> +void decimalToBinary(int num, int *convertedNum);
Надо пустые строки между всеми объявлениями:
```suggestion
#define INT_SIZE (sizeof(int) * 8)

// print a number in binary notation to the console
void printBinaryNumber(int *num);

// converting a number from decimal to binary
void decimalToBinary(int num, int *convertedNum);
```

2024-04-01 18:04 UTC, yurii-litvinov commented on task4-1/binaryAddition.c
> +    sum -= num[0] * current;
Да не нужно знаковый бит специально обрабатывать. Должно и так работать

2024-04-01 18:04 UTC, yurii-litvinov commented on task4-1/binaryAdditionTest.c
> +    int bin[INT_SIZE] = {};
А Си уже умеет пустые инициализаторы? Так более канонично:
```suggestion
    int bin[INT_SIZE] = {0};
```
Справедливости ради, функции без аргументов должны объявляться как `bool testDecimalToBinary(void)`, это ж не C++. Но, опять же справедливости ради, за последними стандартами Си я не слежу.

2024-04-01 18:04 UTC, yurii-litvinov commented on task4-1/binaryAdditionTest.c
> +bool testAddition13Minus15(){
Пробела не хватает

2024-04-01 18:04 UTC, yurii-litvinov commented on task4-1/binaryAdditionTest.c
> +int runAllTestsTask4() {
Оно возвращает только 0 и -1, почему бы ему не быть bool?

2024-04-01 18:10 UTC, Minkerr commented on task4-1/binaryAdditionTest.c
> +int runAllTestsTask4() {
> Оно возвращает только 0 и -1, почему бы ему не быть bool?

Потенциально же может быть больше кодов возврата? Несмотря на это всё равно нужно делать bool если значений два?

2024-04-01 18:42 UTC, Minkerr commented on task4-1/binaryAdditionTest.c
> +int runAllTestsTask4() {
И это для того, чтобы main сразу возвращал результат прогона тестов

2024-04-01 18:42 UTC, Minkerr commented on task4-1/binaryAdditionTest.c
> +int runAllTestsTask4() {
поменял на bool

2024-04-01 18:54 UTC, Minkerr commented
> А у Вас всё ещё удаление main.c в диффах, а не должно быть

Он туда случайно попал опять, так как на момент создания ветки я его не удалил в мастере. Я это должен исправить тем, что удалить из ПР удаление этого файла и просто удалить его локально? Просто локально его у меня уже давно нет, а на отмену удаления из ПР файла мне интернет сказал делать так:
`
git checkout -- путь_к_удаленному_файлу
`
Я ввёл соответственно   
`
git checkout -- main.c  
`
Но он сказал, что такого не нашёл

2024-04-08 12:17 UTC, yurii-litvinov commented
> > А у Вас всё ещё удаление main.c в диффах, а не должно быть
> 
> Он туда случайно попал опять, так как на момент создания ветки я его не удалил в мастере. Я это должен исправить тем, что удалить из ПР удаление этого файла и просто удалить его локально? Просто локально его у меня уже давно нет, а на отмену удаления из ПР файла мне интернет сказал делать так: `git checkout -- путь_к_удаленному_файлу` Я ввёл соответственно `git checkout -- main.c ` Но он сказал, что такого не нашёл

`git checkout` вернёт файл из текущей ветки в рабочую копию, но раз Вы уже закоммитили и запушили изменения, то поздно. Можно его найти в старых версиях и добавить заново (или просто скопировать из диффа). По-хорошему надо было бы откатить из ветки коммит, который его удаляет.

Вообще, если в мастере Вы что-то удалили, а в ветке оно осталось, просто притяните изменения из мастера в ветку, `git pull origin master`.

2024-04-08 12:18 UTC, yurii-litvinov approved these changes
Да, всё хорошо, зачтена

2024-04-08 12:18 UTC, yurii-litvinov commented on task4-1/binaryAddition.c
> +
Лишние пустые строчки :)

2024-05-03 08:39 UTC, merged