add task6-3
Minkerr/Programming1Semester pull request #3
Opened 2024-03-29 10:24 UTC by Minkerr

2024-04-01 09:50 UTC, yurii-litvinov commented on task6-3/list.c
> +    list->length = 0;
Тут все поля забиваются нулевыми значениями, так что вместо malloc можно использовать calloc и тогда вообще записать эту функцию в одну строчку

2024-04-01 09:50 UTC, yurii-litvinov commented on task6-3/list.c
> +    Node *newNode = malloc(sizeof(Node));
Не всё так просто. malloc может вернуть NULL, если аллокация не удалась (например, исчерпали память). Это надо проверять и возвращать код ошибки. Для _каждого_ вызова malloc и каждого вызова функции, которая может завершиться неуспешно (включая Ваши же функции, которые могут завершиться неуспешно из-за того, что внутри что-то завершилось неуспешно). Причём, поскольку ошибку надо корректно сообщить пользователю, надо различать разные виды ошибок (соответственно, иметь разные коды). Поскольку Си не поддерживает исключения, иного пути нет (и в production так реально приходится делать, там даже результат printf проверяют).

2024-04-01 09:50 UTC, yurii-litvinov commented on task6-3/list.c
> +    strcpy(newNode->name, name);
Этот кусок кода прямо просится, чтобы его атаковали переполнением буфера. Никто не обещал, что name и phone поместятся в CAPACITY, и вместе с тем мы можем узнать точный размер name и phone, просто вызвав strlen.

2024-04-01 09:50 UTC, yurii-litvinov commented on task6-3/list.c
> +    if(isEmpty(list)){
Пробелов не хватает

2024-04-01 09:50 UTC, yurii-litvinov commented on task6-3/list.c
> +}
Если список в результате удалился, у вызывающего
- останется "висячий указатель", то есть указатель на освобождённую область памяти, любая операция с которым приведёт к ошибке доступа к памяти и падению программы;
- не будет никакого способа узнать, что список удалился.

Принимайте список как указатель на указатель, и занулите при удалении.

2024-04-01 09:50 UTC, yurii-litvinov commented on task6-3/list.c
> +List *mergeTwoListsByKey(List *first, List *second, enum SortingKey sortingKey) {
Это какая-то очень умная функция для модуля со списком, архитектурно она должна быть в модуле с мерджсортом.

2024-04-01 09:50 UTC, yurii-litvinov commented on task6-3/list.c
> +        int comp;
- Не сокращайте имена.
- Всегда инициализируйте переменные в месте объявления.

2024-04-01 09:50 UTC, yurii-litvinov commented on task6-3/list.c
> +    while (listLen(first) != 0){
Пробелов маловато, и ниже

2024-04-01 09:50 UTC, yurii-litvinov commented on task6-3/list.c
> +List* readFromFile(char* fileName) {
```suggestion
List* readFromFile(const char* const fileName) {
```
Функция же не собирается менять имя файла. Вообще, const в Си не очень полезны, потому что генерируют только предупреждение, но всё же чем их больше, тем лучше.

2024-04-01 09:50 UTC, yurii-litvinov commented on task6-3/list.c
> +    }
Если вычитывать из файла посимвольно, можно сделать умнее и определять размер строки динамически (используйте realloc, если строка перестаёт помещаться)

2024-04-01 09:50 UTC, yurii-litvinov commented on task6-3/list.h
> +typedef enum SortingKey {
Надо комментарии

2024-04-01 09:50 UTC, yurii-litvinov commented on task6-3/main.c
> +int main(){
Пробела не хватает

2024-04-01 09:50 UTC, yurii-litvinov commented on task6-3/main.c
> +    runAllTestsForTask6();
Надо код возврата

2024-04-01 09:50 UTC, yurii-litvinov commented on task6-3/main.c
> +    runAllTestsForTask6();
Надо код возврата

2024-04-01 09:52 UTC, yurii-litvinov requested changes

2024-04-01 09:52 UTC, yurii-litvinov commented on task6-3/mergeSortTest.c
> +    list = mergeSort(list, NAME);
mergeSort может завершиться неуспехом, поэтому затирать list сразу же — выглядит пугающе. Хотя mergesort может гарантировать, что либо она возвращает отсортированный список, либо старое значение, тогда это ок. Но признак успешности операции всё равно нужен, иначе вызывающему непонятно, как узнать, отсортировали его список или нет.

2024-04-01 09:52 UTC, yurii-litvinov commented on task6-3/mergeSortTest.c
> +    if(strcmp(list->head->name, "John") != 0){
Надо больше пробелов

2024-04-01 16:21 UTC, Minkerr commented on task6-3/mergeSortTest.c
> +    list = mergeSort(list, NAME);
Не совсем понял, что делать. Не надо сразу перезаписывать исходный список, на случай, чтобы его не утерять в случае неуспеха?

2024-04-01 22:38 UTC, Minkerr commented on task6-3/list.c
> +}
![image](https://github.com/Minkerr/Programming1Semester/assets/80471496/fa398dd9-de3f-4da1-9a3c-d5e557616002)
Я долго пытался сделать delete на двойном указателе. Тут возникает проблема, что код крашится когда заходит в free(temp->name) или в такой же для phone. Потом я ещё потыкал и даже когда код выглядит примерно как сейчас, с одним указателем, если добавить в конце функции deleteHead проверку на пустоту листа, то он крашится на этом free. Причём он в этот if не заходит ни разу. А если этого ифа нет как сейчас, то всё проходит нормально

2024-04-01 22:39 UTC, Minkerr commented on task6-3/list.c
> +}
При этом tempNode не пустой и всегда нормально определён (на скрине видно)

2024-04-06 17:32 UTC, yurii-litvinov commented on task6-3/mergeSortTest.c
> +    list = mergeSort(list, NAME);
Именно так. Например, если mergeSort возвращает NULL в случае ошибки, стандартный паттерн такой: 
```c
List *temp = mergeSort(list, NAME);
if (temp != NULL) {
    list = temp;
} else {
    deleteList(list);
    return ВСЁ_ПЛОХО;
}
```
Так же с библиотечным realloc, например, делают.

Альтернатива — когда mergeSort в случае ошибки гарантированно возвращает старый список:
```c
Error error = ok;
list = mergeSort(list, NAME, &error);
if (error != ok) {
    deleteList(list);
    return ВСЁ_ПЛОХО;
}
```

2024-04-07 09:36 UTC, yurii-litvinov requested changes

2024-04-07 09:36 UTC, yurii-litvinov commented on task6-3/list.c
> +    return list;
```suggestion
    return calloc(1, sizeof(List));
```

2024-04-07 09:36 UTC, yurii-litvinov commented on task6-3/list.c
> +int add(List *list, char *name, char *phone) {
Лучше для кодов возврата enum заводить. Это по сути ничего не даёт, потому что в Си enum-ы — это просто набор констант, и компилятор их от int-ов не отличает, но лучше понятно, что это именно код ошибки, а не просто какой-то int.

2024-04-07 09:36 UTC, yurii-litvinov commented on task6-3/list.c
> +        return MEMORY_ALLOCATION_ERROR;
Не так просто — мы могли успеть выделить память под name, но на phone она закончилась. Тогда надо действительно вернуть MEMORY_ALLOCATION_ERROR, но и удалить newNode->name не забыть. Для встроенных систем (а именно их в основном программируют на Си) это может быть критично.

2024-04-07 09:36 UTC, yurii-litvinov commented on task6-3/list.c
> +        (list)->head = (list)->head->next;
```suggestion
        Node *tempHead = list->head;
        list->head = list->head->next;
```

2024-04-07 09:36 UTC, yurii-litvinov commented on task6-3/list.c
> +}
```suggestion
void deleteList(List **list) {
    while (!isEmpty(*list)) {
        deleteHead(*list);
    }
    free(*list);
    *list = NULL;
}
```

2024-04-07 09:36 UTC, yurii-litvinov commented on task6-3/list.c
> +    return list->length;
Если уж совсем хорошо делать, надо и list на NULL проверять, и возвращать код ошибки. Но это можно не править.

2024-04-07 09:36 UTC, yurii-litvinov commented on task6-3/list.c
> +    FILE *file = fopen(fileName, "r");
Это может закончиться неудачей, файла может не быть

2024-04-07 09:36 UTC, yurii-litvinov commented on task6-3/list.c
> +    List *list = initList();
initList может вернуть NULL

2024-04-07 09:36 UTC, yurii-litvinov commented on task6-3/list.c
> +                char *newLine = realloc(line, (lineSize + CAPACITY) * sizeof(char));
Под line память реаллоцируется, но под name и phone нет. Так что strcpy выше страшно издохнут с Segmentation Fault, если строка в них не влезет.

2024-04-07 09:36 UTC, yurii-litvinov commented on task6-3/list.c
> +                    return NULL;
Если реаллокаця не удалась, это не повод оставлять в памяти name, phone и предыдущий line

2024-04-07 09:36 UTC, yurii-litvinov commented on task6-3/list.c
> +    return list;
А тут даже если ошибки нет, будет утечка памяти, потому что временные буферы никто не чистит

2024-04-07 09:36 UTC, yurii-litvinov commented on task6-3/list.h
> +} List;
По принципу сокрытия деталей реализации нельзя структуры определять в .h-никах. Формат хранения данных в памяти — внутреннее дело модуля, внешний мир может с ним работать только через интерфейс, состоящий только из функций и "интерфейсных" структур данных (которые принимают-возвращают функции и которые по смыслу часть интерфейса модуля, а не его реализации).

2024-04-07 09:36 UTC, yurii-litvinov commented on task6-3/mergeSort.c
> +                                                   : strcmp(first->head->name, second->head->name);
Весь смысл этой задачи был в том, чтобы научиться писать архитектурно осмысленные абстракции, интерфейса которых достаточно для реализации даже нетривиальных алгоритмов.

2024-04-07 09:36 UTC, yurii-litvinov commented on task6-3/mergeSortTest.c
> +    bool res = true;
Не сокращайте имена

2024-04-08 18:09 UTC, Minkerr commented on task6-3/mergeSort.c
> +                                                   : strcmp(first->head->name, second->head->name);
Не совсем понял, что именно в этих строках не так

2024-05-03 08:40 UTC, merged