add task7-2
Minkerr/Programming1Semester pull request #4
Opened 2024-03-29 18:22 UTC by Minkerr

2024-04-01 09:58 UTC, yurii-litvinov requested changes

2024-04-01 09:58 UTC, yurii-litvinov commented on task7-2/expressionTree.c
> +#define STRING_SIZE 64
Тут тоже, надо усовершенствовать подсистему ввода строк, чтобы не делать предположений об их размере.

2024-04-01 09:58 UTC, yurii-litvinov commented on task7-2/expressionTree.c
> +    char *string = malloc(STRING_SIZE * sizeof(char));
И тоже реализовать механизм сигнализации об ошибках.

2024-04-01 09:58 UTC, yurii-litvinov commented on task7-2/expressionTree.c
> +}
sscanf?

2024-04-01 09:58 UTC, yurii-litvinov commented on task7-2/expressionTree.c
> +                                                              ((str[i + 1] <= '0') || (str[i + 1] >= '9'));
Что-то злое с отступами

2024-04-01 09:58 UTC, yurii-litvinov commented on task7-2/expressionTree.c
> +    if(isNodeANumber(node)){
Пробелов маловато

2024-04-01 09:58 UTC, yurii-litvinov commented on task7-2/expressionTree.h
> +typedef struct Tree Tree;
Надо комментарии

2024-04-01 09:58 UTC, yurii-litvinov commented on task7-2/expressionTreeTest.c
> +bool testExpTree(){
ExperienceTree? Не сокращайте идентификаторы

2024-04-01 09:58 UTC, yurii-litvinov commented on task7-2/main.c
> +    runAllTestsForTask7();
Если тесты не прошли, основной код вообще не должен запускаться.

2024-04-01 17:39 UTC, Minkerr commented on task7-2/expressionTree.c
> +                                                              ((str[i + 1] <= '0') || (str[i + 1] >= '9'));
А как следует? Для такого переноса CLion рекомендует выравнивать так

2024-04-08 12:21 UTC, yurii-litvinov commented on task7-2/expressionTree.c
> +                                                              ((str[i + 1] <= '0') || (str[i + 1] >= '9'));
Один отступ для строки-продолжения, или два, чтобы отличать её от "структурного" отступа. CLion вообще неправ — код сильно смещён вправо, и если потребуется ещё перенос, ещё вправо уедет, плюс при рефакторинге выравнивание всё равно испортится.

2024-04-08 12:31 UTC, yurii-litvinov requested changes

2024-04-08 12:31 UTC, yurii-litvinov commented on task7-2/expressionTree.c
> +}
```suggestion
Tree *initTree() {
    return сalloc(sizeof(Tree));
}
```
Иначе вызывающему возвращается структура с мусором в поле root. Который он, наверное, перезапишет, но а если нет?

2024-04-08 12:31 UTC, yurii-litvinov commented on task7-2/expressionTree.c
> +        return NULL;
А файл ещё закрыть надо. Вообще, если берёте какой-то ресурс (открываете файл, выделяете память), то на всех путях исполнения функции он обязательно освобождается, либо отдаётся вызывающему в том или ином виде (например, подвешивается к дереву или ещё что-то).

2024-04-08 12:31 UTC, yurii-litvinov commented on task7-2/expressionTree.c
> +                return NULL;
Надо освободить старую line и закрыть файл

2024-04-08 12:31 UTC, yurii-litvinov commented on task7-2/expressionTree.c
> +    if (str == NULL) {
str может быть NULL только в самом начале, так что эту проверку стоило бы вынести в parseTreeFromString

2024-04-08 12:31 UTC, yurii-litvinov commented on task7-2/expressionTree.c
> +    Tree *tree = initTree();
Может вернуть NULL, нужна проверка, тут и во многих других местах, где функция может вернуть NULL

2024-04-08 12:31 UTC, yurii-litvinov commented on task7-2/expressionTree.c
> +}
```suggestion
void deleteTree(Tree **tree) {
    deleteTreeRecursive((*tree)->root);
    free(*tree);
    *tree = NULL;
}
```

2024-04-08 12:31 UTC, yurii-litvinov commented on task7-2/expressionTree.h
> +// a binary tree that implements an expression tree that can calculate an expression
```suggestion
#pragma once

// a binary tree that implements an expression tree that can calculate an expression
```

2024-04-08 12:31 UTC, yurii-litvinov commented on task7-2/expressionTree.h
> +char *readStringFromFile(char *fileName);
```suggestion
char *readStringFromFile(const char * const fileName);
```

2024-04-08 12:31 UTC, yurii-litvinov commented on task7-2/expressionTreeTest.c
> +}
Что-то как-то тестов маловато

2024-04-08 12:31 UTC, yurii-litvinov commented on task7-2/expressionTreeTest.c
> +    bool res = calculate(tree) == 4;
Не сокращайте имена

2024-05-03 08:40 UTC, merged