add task10-1
Minkerr/Programming1Semester pull request #7
Opened 2024-03-30 18:37 UTC by Minkerr

2024-04-01 12:07 UTC, yurii-litvinov requested changes

2024-04-01 12:07 UTC, yurii-litvinov commented on task10-1/graph.c
> +#define INF 1000000
Если это "бесконечность", можно использовать более определённое значение, например, библиотечный макрос INT_MAX. И не сокращайте имена никогда, Вы же не в блокнотике программируете — их надо написать один раз, дальше среда разработки их сама подставлять будет.

2024-04-01 12:07 UTC, yurii-litvinov commented on task10-1/graph.c
> +}
Надо какой-то сигнал об ошибке, если условие if неверно. Код ошибки возвращать, например.

2024-04-01 12:07 UTC, yurii-litvinov commented on task10-1/graph.c
> +}
И занулить указатель

2024-04-01 12:07 UTC, yurii-litvinov commented on task10-1/graph.c
> +    int min = INF, minIndex;
Не объявляйте две переменные одновременно, каждая заслуживает своей отдельной декларации (и инициализации).

2024-04-01 12:07 UTC, yurii-litvinov commented on task10-1/graph.c
> +    int visited[size];
Если это по смыслу булевый массив, надо его объявить как bool.

2024-04-01 12:07 UTC, yurii-litvinov commented on task10-1/graph.c
> +    FILE *file = fopen(fileName, "r");
Файла может не быть.

2024-04-01 12:07 UTC, yurii-litvinov commented on task10-1/graph.c
> +        int len;
Куча неинициализированных переменных

2024-04-01 12:07 UTC, yurii-litvinov commented on task10-1/graph.c
> +    graph->governmentMarks[minIndex] = graph->governmentMarks[capital]; //mark the found the nearest city with a number of capital
Комментарий как-то не очень по-английски

2024-04-01 12:07 UTC, yurii-litvinov commented on task10-1/graph.c
> +        markTheNearestNotMarkedVertex(graph, listOfCapitals[counter]);
Этак государства смогут захватывать города, телепортируясь через чужие. Например, если есть три города и два государства, `(A)---(B)---( )`, то государство A захватит на первом ходу ничейный город, хотя в правильном решении не смогло бы это сделать.

2024-04-01 12:07 UTC, yurii-litvinov commented on task10-1/graph.h
> +Graph *initGraph(int num);
Надо комментарии

2024-04-01 12:07 UTC, yurii-litvinov commented on task10-1/graphTest.c
> +#include "graph.c"
Так нельзя

2024-04-01 12:07 UTC, yurii-litvinov commented on task10-1/graphTest.c
> +bool testForInputData(){
Пробелов не хватает

2024-04-01 12:07 UTC, yurii-litvinov commented on task10-1/graphTest.c
> +#include "stdio.h"
Тут угловые скобки должны быть

2024-04-01 12:07 UTC, yurii-litvinov commented on task10-1/main.c
> +    runTestForInputData();
Надо ненулевой код возврата, если тесты не прошли

2024-04-02 06:28 UTC, Minkerr commented on task10-1/graph.c
> +        markTheNearestNotMarkedVertex(graph, listOfCapitals[counter]);
Ой, там даже для тех входных, которые есть, прыжок совершается. Не обдумал этот момент.

Исправил

2024-04-08 14:02 UTC, yurii-litvinov requested changes

2024-04-08 14:02 UTC, yurii-litvinov commented on task10-1/graph.c
> +        return INCORRECT_INPUT;
Тут INCORRECT_INPUT определяется в .c, а возвращается вовне. Проблема в том, что "вовне" не имеет идей, что такое INCORRECT_INPUT, так что верно интерпретировать значение по смыслу не может (ну, так-то может просто проверять интовое значение, но не человекочитаемое INCORRECT_INPUT). Так что INCORRECT_INPUT относится к интерфейсной части модуля и должно быть определено в .h

2024-04-08 14:02 UTC, yurii-litvinov commented on task10-1/graph.c
> +    graph->vertexNum = num;
malloc может NULL вернуть

2024-04-08 14:02 UTC, yurii-litvinov commented on task10-1/graph.c
> +    graph = NULL;
Это бесполезно :) `*graph = NULL;`, конечно же

2024-04-08 14:02 UTC, yurii-litvinov commented on task10-1/graph.c
> +    fscanf_s(file, "%d %d", &n, &m);
При некорректном файле fscanf_s может завершиться неудачей, так что и это тоже надо проверять по-хорошему. Но это придирка и можно не править :)

2024-04-08 14:02 UTC, yurii-litvinov commented on task10-1/graph.c
> +    Graph *graph = initGraph(n);
А вот тут точно надо проверять, потому что initGraph всегда может случайно вернуть NULL

2024-04-08 14:02 UTC, yurii-litvinov commented on task10-1/graph.c
> +            return NULL;
Надо закрыть файл и удалить граф

2024-04-08 14:02 UTC, yurii-litvinov commented on task10-1/graph.c
> +            dijkstra(graph, i);
Вы взяли первоначальный неправильный алгоритм и затюнинговали его так, чтобы он таки заработал. Что теперь происходит:
- мы по изначальному графу гоним Дейкстру, чтобы для каждой столицы узнать стоимости путей до каждой достижимой с учётом стартовой ситуации вершины графа
- далее мы на каждом шагу гоним DFS, чтобы обновить данные о достижимости
- затем мы выбираем "ближайшую" из достижимых вершин, пользуясь расстояниями, полученными Дейкстрой.

Тут две проблемы:
- матрицу расстояний так-то надо обновлять каждый ход, потому что враг может отрезать кратчайший путь до полюбившегося нам города, и если мы до него когда-нибудь доберёмся, он может перестать быть приоритетным для завоевания
- мы на каждом шагу алгоритма проверяем достижимость до всех вершин графа, хотя нас интересуют только ближайшие наши соседи, так что зря тратим вычислительные ресурсы

Так что правильным решением тут было бы на каждом ходу для каждого государства выбирать ближайший город из незанятых на расстоянии одного ребра от всех городов государства и захватывать его. Это как бы Дейкстра, которую одновременно гонят из нескольких начальных вершин.

Из-за весьма близкого зачёта это можно не переделывать. Ваш алгоритм по трудоёмкости где-то на O(n) больше того, что нужно, но должен работать.

2024-04-08 14:02 UTC, yurii-litvinov commented on task10-1/graphTest.c
> +    bool res = graph->governmentMarks[1] == 1
Не сокращайте идентификаторы

2024-05-03 08:40 UTC, merged